### ISSUE TITLE
[Tracking issue] Switch to mock response testing

### ISSUE THREAD

**Issue by indigok** [octokit/octokit.rb#1258]
Octokit currently uses [vcr](https://github.com/vcr/vcr)'s during testing. This has helped avoid making real time api calls while keeping the accuracy of real payloads. However, cassettes grow outdated if they're not consistently rerecorded (a lot of ours are from 2013 😬) and can been a little finicky when recording new ones, whether it's keeping out hard-coded values or getting the right permissions.

With this proposal, we're moving towards using a mock server, [octokit/fixtures-server](https://github.com/octokit/fixtures-server). This keeps the payloads up to date for us and we can easily swap them in during the api calls, plus it's also used by the JS SDK. This server only has 22 [`scenarios`](https://github.com/octokit/fixtures/tree/master/scenarios/api.github.com/) which roughly map to endpoints. But, as we're moving towards generating this SDK in #1157, this is sufficient for our purposes. Having a generated SDK means we can test the generation, and several basic and edge cases in the api, and still be confident in the quality.

A working flow of this was opened in #1256  with the `get-repository` scenario and updates to our testing action.

And here's a tracking list of all the scenarios to add tests for:
- [ ] add-and-remove-repository-collaborator
- [ ] add-labels-to-issue
- [ ] branch-protection
- [ ] create-file
- [ ] create-status
- [ ] errors
- [ ] get-archive
- [ ] get-content
- [ ] get-organization
- [x] get-repository
- [ ] get-root
- [ ] git-refs
- [ ] labels
- [ ] lock-issue
- [ ] mark-notifications-as-read
- [ ] markdown
- [ ] paginate-issues
- [ ] project-cards
- [ ] release-assets-conflict
- [ ] release-assets
- [ ] rename-repository
- [ ] search-issues

These are in alphabetical order, and would probably be best to implement them slightly differently. For example, start with the `get` scenarios as they should be fairly basic and/or clients that are already auto-generated and work up from there.

/cc: @jovel

**Comment by mommadukes1** [comment]
Lissamjay
