### ISSUE TITLE
2.0.0

### ISSUE THREAD

**Issue by pengwynn** [octokit/octokit.rb#273]
Roadmap and ship list for [Octokit.rb 2.0.0](https://github.com/octokit/octokit.rb/tree/octokit-2).
### Highlights
- First hypermedia-enabled release, powered by [Sawyer](https://github.com/lostisland/sawyer). Responses are now parsed into Resource attributes and hypermedia link Relations. Version 3.0.0 will be hypermedia-driven (no URL construction).
- [VCR](https://github.com/vcr/vcr) for more accurate spec fixtures.
- Refactored `Connection` module for smarter, memoized connections based on configuration options that support [HTTP caching](https://github.com/plataformatec/faraday-http-cache) middleware.
- More robust `Configuration` module inspired by the Twitter gem, supporting environment variables for most settings.
- The `last_response` convenience method to access raw HTTP responses for the last call, including pagination links. 
### TODO
- [x] Move to access token instead of Basic Auth for test suite
- [x] Finish refactoring specs to use JSON format for 1.9.3 and 2.0.0 Ruby support.
- [x] Finish refactoring specs to use new GitHub repo location
- [x] Upgrade to Faraday 0.9 #272 
- [x] Handle labels as array or list #271 
- [x] Method to get authorize url #258
