### ISSUE TITLE
Release v4.8.0?

### ISSUE THREAD

**Issue by greysteil** [octokit/octokit.rb#952]
It's been a while since the last release (which was in March) and there are a *lot* of [changes on master](https://github.com/octokit/octokit.rb/compare/v4.7.0...master). Would be rad to get them released - is there anything blocking?

**Comment by tarebyte** [comment]
We agree that we need to cut a release, sorry it's been a while 😅 

# TODO
- [ ] Write up the changelog
- [ ] Ensure there aren't any breaking changes
- [ ] If there breaking changes cut a branch release candidate for 4.8.0 and another for 5.0.0
- [ ] Run rake task to send release(s) to Rubygems and GitHub
- [ ] Post change log to release notes

**Comment by kytrinyx** [comment]
## TODO
https://github.com/octokit/octokit.rb/pull/892 removes support for the deprecated Integrations namespace, replacing it with `Apps`. I think we need to assign `Apps` to a new constant `Integrations` so that we don't cause a backwards-incompatible change.

## Changelog notes

Using https://github.com/octokit/octokit.rb/compare/v4.7.0...master

We have been unable to get a rubinius build working for CI for quite some time, meaning that rubinius support has been spotty or non-existent. We've stopped trying. Not backwards-incompatible directly since it already wasn't working, but a little bit iffy anyway.

**Add support for additional API endpoints**
* Add support for Topics #885
* Add support for Get a single Installation #884
* Add support for Add assignees #894
* Add support for Find user installations #895
* Add support for marketplace listings API #929
* Add support for the new Nested Teams API preview #928
* Add support for Get user's marketplace purchases #938
* Add support for new apps endpoint #932

**Tweak behavior**
* Allow reviews and review comments to be paginated #886
* Expose response_headers and response_body on error objects #899
* Remove destructive assignment for repository #876
* Improve error message when `Octokit::Repository.new` fails #877
* Take the Organization Memberships API out of preview #913
* Take the Pull Request Review API out of preview #923
* Update add/remove installations methods to use non-deprecated endpoints #958
* Fix apps client for GitHub Enterprise installs (new endpoints in this release, but still) #966

**Comment by kytrinyx** [comment]
Wait. It says that #892 aliases the namespace. I can't see which line. Looking more carefully.

**Comment by kytrinyx** [comment]
Oh, I see what's going on. We don't actually reference the namespace directly (e.g. Octokit::Client::App). So this is fine.

Sorry about the kerfuffle!

**Comment by kytrinyx** [comment]
Alrighty! Here it is: https://github.com/octokit/octokit.rb/releases/tag/v4.8.0

**Comment by greysteil** [comment]
🎉
